# This is a basic workflow to help you get started with Actions

name: Merge-Main
on:
  push:
    branches: 
      - main
  workflow_dispatch:

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: call merge main rest api
        run: |
          curl \
          -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "content-type: application/json" \
          -H "authorization: Bearer ${{ secrets.ACCESS_TOKEN }}" \
          https://github.com/AutumnWhj/GithubAction/merges \
          -d '{"base":"dev","head":"main"}'
